import { E164Number } from "libphonenumber-js/core";

export type BeMyAgentFormType = Partial<{
  searchName?: string;
  propertyType: [];
  priceRangeMinimum: string;
  priceRangeMaximum: string;
  bedMinimum: string;
  bedMaximum: string;
  bathroomMinimum: string;
  bathroomMaximum: string;
  rentAdvanceOptions: [];
  locationArray: {
    city: string;
    neighbourhood: string;
  }[];
  utilities: [];
  featuresAndAmenities: [];
  title: string;
  firstName: string;
  lastName: string;
  gender: string;
  tenants: string;
  moveInDate: string;
  leaseTerm: number;
  leaseTermMinimum: string;
  leaseTermMaximum: string;
  paymentOption: string;
  maritalStatus: string;
  email: string;
  country: string;
  city: string;
  phoneNumber: string | E164Number;
  availableOnWhatsapp: boolean;
  preferredMethodOfContact: "email" | "whatsapp";
  currentAddress1: string | boolean;
  currentAddress2: string;
  reasonsForMoving: string;
  mostRecentEmployment: string;
  currentlyEmployed: string;
  employmentStartDate: string;
  employmentEndDate: string;
  employersCountry: string;
  employer: string;
  // employerAddress1: string;
  // employerAddress2: string;
  // employerPhoneNumber: string;
  jobTitle: string;
  monthlyIncome: string;
  monthlyIncomeCurrency: string;
  dateOfBirth: string;
  identificationType: string;
  idNumber: string;
  government: string;
  evictedBefore: string;
  convictedBefore: string;
  reasonForConviction: string;
  reasonForEviction: string;
  pets: string;
  petDetails: string;
  vehicles: string;
}>;

export type ProcessSummary = {
  currentSummaryPage: string;
};
