import { getFeatureIcon, getPropertyTypeIcon } from "@/lib/utils/getFeatureIcon";


export const properties = [
  { name: "house", icon: getPropertyTypeIcon("house") },
  { name: "compound house", icon: getPropertyTypeIcon("compound house") },
  { name: "town house", icon: getPropertyTypeIcon("town house") },
  { name: "apartment", icon: getPropertyTypeIcon("apartment") },
  { name: "flats", icon: getPropertyTypeIcon("flats") },
  { name: "room", icon: getPropertyTypeIcon("room") },
  { name: "guest house", icon: getPropertyTypeIcon("guest house") },
  { name: "chamber and hall", icon: getPropertyTypeIcon("chamber and hall") },
  { name: "boys quarters", icon: getPropertyTypeIcon("boys quarters") },
  { name: "hostel", icon: getPropertyTypeIcon("hostel") },
];

export const requiredFeatures = [
  { name: "wifi", icon: getFeatureIcon("wifi") },
  { name: "satellite tv", icon: getFeatureIcon("satellite tv") },
  { name: "pets allowed", icon: getFeatureIcon("pets allowed") },
  { name: "near road", icon: getFeatureIcon("near road") },
  { name: "security camera", icon: getFeatureIcon("security camera") },
  { name: "kitchen", icon: getFeatureIcon("kitchen") },
  { name: "air conditioning", icon: getFeatureIcon("air conditioning") },
  { name: "elevator", icon: getFeatureIcon("elevator") },
  { name: "generator", icon: getFeatureIcon("generator") },
  { name: "water", icon: getFeatureIcon("water") },
  { name: "fan", icon: getFeatureIcon("fan") },
  { name: "electricty", icon: getFeatureIcon("electricty") },
  { name: "refrigerator", icon: getFeatureIcon("refrigerator") },
  { name: "gas", icon: getFeatureIcon("gas") },
  { name: "microwave", icon: getFeatureIcon("microwave") },
  { name: "self meter", icon: getFeatureIcon("self meter") },
  { name: "polytank", icon: getFeatureIcon("polytank") },
  { name: "walled & gated", icon: getFeatureIcon("walled & gated") },
  { name: "parking", icon: getFeatureIcon("parking") },
  { name: "landlord on site", icon: getFeatureIcon("landlord on site") },
  { name: "landlord off site", icon: getFeatureIcon("landlord off site") },
  { name: "tiled space", icon: getFeatureIcon("tiled space") },
  { name: "self contained", icon: getFeatureIcon("self contained") },
  { name: "dish washer", icon: getFeatureIcon("dish washer") },
  { name: "washing machine", icon: getFeatureIcon("washing machine") },
  { name: "security guard", icon: getFeatureIcon("security guard") },
  { name: "fully furnished", icon: getFeatureIcon("fully furnished") },
  { name: "semi furnished", icon: getFeatureIcon("semi furnished") },
  { name: "unfurnished", icon: getFeatureIcon("unfurnished") },
 ];
